name: CL-RDP-Ngrok

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download Ngrok (Fixed Link)
      run: |
        Invoke-WebRequest https://bin.equinox.io/a/4hREUYJSmzd/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

    - name: Extract Ngrok
      run: |
        Expand-Archive ngrok.zip -DestinationPath ngrok

    - name: Authenticate Ngrok
      run: |
        .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable RDP Securely
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

        $pass = [System.Web.Security.Membership]::GeneratePassword(20,4)
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString $pass -AsPlainText -Force)

        Write-Output "======================================"
        Write-Output "RDP USER: runneradmin"
        Write-Output "RDP PASS: $pass"
        Write-Output "======================================"

    - name: Start Ngrok TCP Tunnel (10 Minutes Only)
      run: |
        Write-Output "Starting Ngrok RDP Tunnel for 10 minutes..."
        timeout 10m .\ngrok\ngrok.exe tcp 3389
